#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const artifactsDir = path.join(rootDir, 'src', 'artifacts');
const publicDir = path.join(rootDir, 'public');
const outputFile = path.join(publicDir, 'artifacts-data.js');

function buildArtifactsData() {
  // Ensure public directory exists
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }

  const artifacts = [];

  if (!fs.existsSync(artifactsDir)) {
    fs.writeFileSync(outputFile, 'window.ARTIFACTS_DATA = [];');
    console.log('No artifacts directory found. Created empty artifacts-data.js');
    return;
  }

  const dirs = fs.readdirSync(artifactsDir).filter((name) => {
    const artifactPath = path.join(artifactsDir, name);
    return fs.statSync(artifactPath).isDirectory();
  });

  dirs.forEach((slug) => {
    const metaPath = path.join(artifactsDir, slug, 'meta.json');
    const indexPath = path.join(artifactsDir, slug, 'index.html');

    if (!fs.existsSync(indexPath)) {
      return;
    }

    let meta = {
      name: slug,
      description: 'No description available',
      tags: [],
      created: '',
      thumbnail: '',
      hidden: false,
    };

    if (fs.existsSync(metaPath)) {
      try {
        const metaContent = JSON.parse(fs.readFileSync(metaPath, 'utf-8'));
        meta = { ...meta, ...metaContent };
      } catch (e) {
        console.warn(`Warning: Could not parse meta.json for ${slug}`);
      }
    }

    // Skip hidden artifacts
    if (meta.hidden) {
      console.log(`Skipping hidden artifact: ${slug}`);
      return;
    }

    artifacts.push({
      slug,
      name: meta.name,
      description: meta.description,
      tags: meta.tags,
      created: meta.created,
      thumbnail: meta.thumbnail ? `./src/artifacts/${slug}/${meta.thumbnail}` : '',
      path: `./src/artifacts/${slug}/index.html`,
    });
  });

  // Sort by creation date (newest first)
  artifacts.sort((a, b) => {
    if (!a.created) return 1;
    if (!b.created) return -1;
    return new Date(b.created) - new Date(a.created);
  });

  const output = `// Auto-generated by build-index.js - do not edit manually
window.ARTIFACTS_DATA = ${JSON.stringify(artifacts, null, 2)};
`;

  fs.writeFileSync(outputFile, output);
  console.log(`Generated artifacts-data.js with ${artifacts.length} artifact(s)`);
}

buildArtifactsData();
